# Site settings
title: lotteries.io
email: your-email@domain.com
description: building a generic api for lottery operations
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lotteries.io" # the base hostname & protocol for your site
github_username:  lotteries-io
permalink: /:title

# collections
collections:
  link-relationships:
    output: true
  gaming-products:
    output: true
  application-profiles:
    output: true
  concepts:
    output: true
  properties:
    output: true
  problem-types:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
